version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mean-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/message-post-db
    depends_on:
      - mongo
    networks:
      - mean-network

  frontend:
    build: ./angulare-app/message-app/
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mean-network

networks:
  mean-network:
